version: '3.8'
services:
    voting:
      image: megbrn/vote:1.0
      ports: 
        - 5000:80
      links:
        - "redis:redis"
    redis:
      image: redis
    db:
      image: postgres
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
      ports:
        - "5432:5432"  
    worker:
      image: megbrn/work:1.0
      links:
        - "db:db"
        - "redis:redis"
    result:
      image: megbrn/result:1.0
      ports:
        - 5001:80
      links:
        - "db:db"
