apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: worker
      env:
      - name: DB_SERVICE
        value: "db:5432"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker
  name: worker
  namespace: vote
spec:
  type: ClusterIP
  ports:
  selector:
    app: worker